
name: CI Run
on: [push]

env:
  MY_ENV_VAR: FLIPPER

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test 1 - PASS"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: echo "Test 2 - FAIL" ; exit 1